// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210920161213_GraoAcordos")]
    partial class GraoAcordos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("API.Entities.Acordo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contrato")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GraoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Variacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GraoId");

                    b.ToTable("Acordos");
                });

            modelBuilder.Entity("API.Entities.Grao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Graos");
                });

            modelBuilder.Entity("API.Entities.Acordo", b =>
                {
                    b.HasOne("API.Entities.Grao", "Grao")
                        .WithMany("Acordos")
                        .HasForeignKey("GraoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grao");
                });

            modelBuilder.Entity("API.Entities.Grao", b =>
                {
                    b.Navigation("Acordos");
                });
#pragma warning restore 612, 618
        }
    }
}
